### ISSUE TITLE
Update to 10.3.18

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/mariadb103#1]
This RPM spec file needs to be updated to [upstream version 10.3.18](https://mariadb.com/kb/en/library/mariadb-10318-release-notes/).  If you aren't familiar with RPM spec files, check out [this guide](https://rpm-packaging-guide.github.io).  The end result should look something [like this](https://github.com/iusrepo/mariadb103/commit/e9ba2a6e76d3eafc7976bb538a00b83c57942291).

**Comment by RahulRavishankar** [comment]
Hey, I'm interested in working on it

**Comment by RahulRavishankar** [comment]
I've sent a pull request. Please do review it.

**Comment by carlwgeorge** [comment]
fixed in #2
