### ISSUE TITLE
old dependency for common and server packages

### ISSUE THREAD

**Issue by simplesalt** [iusrepo/mariadb103#6]
I use the ius repo and recently installed mariadb 10.3.  I'm not sure if this is right place to note it, but:
```
mariadb103-common-3:10.3.21-2.el7.ius.x86_64
mariadb103-server-3:10.3.21-2.el7.ius.x86_64
```
both list: 
`mariadb-libs.x86_64                1:5.5.65-1.el7                @base`
as a dependency.  Should they maybe list the equivalent package in 10.3 instead?
`mariadb103-libs.x86_64             3:10.3.21-2.el7.ius           @ius`

**Comment by carlwgeorge** [comment]
Thanks for reaching out, but this is intentional.  mariadb103 uses the `/etc/my.cnf` file from mariadb-libs.  mariadb-libs and mariadb103-libs provide different libraries.  It's described in more detail [here](https://github.com/iusrepo/mariadb103/wiki#implementation).

**Comment by simplesalt** [comment]
Brilliant.  Thanks again for your hard work.  I really appreciate it.
